config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'articles#index'
  get 'admin', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_rich_text :body
    
    extend FriendlyId
    friendly_id :title, use: :slugged

    validates_presence_of :title

    def self.published
        Article.where(published: :true)
    end
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, uniqueness: true, presence: true
    validates_presence_of :password, require: true

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :registered_user, :not_found_404

    def registered_user
        @registered_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def not_found_404
        render file: "#{Rails.root}/public/404.html"
    end

    def require_registered_user
        not_found_404 unless registered_user
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :require_registered_user, only: [:new, :create]

    def index
        @articles = Article.published
    end

    def show
        @article = Article.friendly.find(params[:id])

        @article.published or registered_user ? @article : not_found_404
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)

        if @article.save()
            redirect_to @article, notice: "Article created successfully"
        else
            render :new
        end
    end

    private
    def article_params
        params.require(:article).permit(:title, :body, :published)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        user = User.find_by(username: params[:username])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path
        else
            render new
        end
    end

    def destroy
        session.clear
        redirect_to root_path
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/index.html.erb
<main>
    <% @articles.each do |article| %>
      <%= content_tag :article do %>
         <%= link_to article.title, article_path(article), class: 'article-title' %>
         <%= article.body %>
      <% end %>
    <% end %>
</main>
<section>
   <%# This is where tags or other navigation will go %>
</section>

app/views/articles/new.html.erb
<div class='full-page'>
    <%= form_with(model: @article, local: true) do |f| %>
        <% if @article.errors.any? %>
            <%= render partial: 'partials/error_message', locals: {errors: @article.errors, consequence: 'prevented this article from saving'} %>
        <% end %>

        <%= f.label :title%>
        <%= f.text_field :title%>

        <%= f.label :body%>
        <%= f.rich_text_area :body%>

        <%= f.label :published%>
        <%= f.check_box :published%>

        <%= f.submit 'Create article' %>
    <% end %>
</div>

app/views/articles/show.html.erb
<div class='full-page'>
    <h2 class='article-title'><%= @article.title %> </h2>
    <body>
        <%= @article.body %>
    </body>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'partials/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/partials/_error_message.html.erb
<div class='error-message'>
    <h2>
        <%= "#{pluralize(errors.count(), 'error')} #{consequence}" %>
    </h2>
    <ul>
        <% errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    </ul>
</div>

app/views/partials/_navigation.html.erb
<nav>
    <%= image_pack_tag('media/images/Home.png', alt:'Home', class:'nav-home') %>
    <ol class='admin-nav'>
        <% if registered_user %>
            <li>
                <%= link_to 'Log out', logout_path %>
            </li>
            <li>
                <%= link_to 'Create new article', new_article_path %>
            </li>
        <% end %>
    </ol>
    <%= image_pack_tag('media/images/Questions.png', alt:'Why?', class:'nav-why') %>
</nav>